### PR TITLE
Add usage notes to README

### PR DESCRIPTION
**Pull request by creuter**

### CODE REVIEW

**Comment by tysongach** [comment]
Does running `middleman init MY_PROJECT_FOLDER -T thoughtbot/middleman-template` work for you? I get an error when I try it.

If I remember correctly, Middleman templates require an explicit structure, with a root `template/` directory. That didn't jive with Netlify's one-click deploy button, so we had to choose one way or the other. Not sure which is best.

**Comment by creuter** [comment]
I thought I could, but missed the `T` flag. I'm now having dependency trouble which I'm trying to resolve. Will report back.

**Comment by creuter** [comment]
I'm going to close this, since I'm still getting rb-fsevent dependency errors that I can't resolve.

**Comment by tysongach** [comment]
After digging into this, I think the errors we were seeing were just temporary dependency issues.

Running `middleman init PROJECT_NAME --template=thoughtbot/middleman-template` works for me, now.

I've opened https://github.com/thoughtbot/middleman-template/pull/34 which swaps the Netlify button for the Middleman CLI.

In the future, I'd like to investigate using Netlify's CLI to spin up a new site instance after generating the template.

**Pull request closed without merging**
